### PR TITLE
fix(perf): replace query rewrite with graph-indexed header

### LINKED ISSUE #900: remove query rewrites
After release 2.1.1, client query rewrites are only required for inserting the probe for block data. Ideally we would remove the error-prone rewrite code in favor of independent queries to indexers for that block data. These queries can be far less frequent than client queries typically are for each subgraph chain.

### PR DESCRIPTION
**Pull request by Theodus**
This remove rewrites that insert an additional `_meta` query to probe indexing progress on every query. Assuming sufficient indexer support for the `graph-indexed` header, then this should be a safe removal.

Resolves #900

### CODE REVIEW

File: src/indexer_client.rs [hunk 1]
```diff
@@ -22,7 +22,7 @@ use crate::{
 
 #[derive(Clone, Debug)]
 pub struct IndexerResponse {
-    pub original_response: String,
+    pub indexer_response: String,
```
Comment (tmigone) [inline src/indexer_client.rs]: I think we no longer need to have both `indexer_response` and `client_response`, this was needed before when one of them had the gateway probe meta query response, but now these two are the same.

Comment (tmigone) [reply src/indexer_client.rs]: We should probably remove `client_response`

**Review by tmigone — CHANGES_REQUESTED** [review]

File: src/indexer_client.rs (hunk 1 above)
Comment (Theodus) [reply src/indexer_client.rs]: Good catch. Fixed in ae5e271

**Review by tmigone — APPROVED** [review]
